### ISSUE TITLE
Start and end joint

### ISSUE THREAD

**Issue by ebarsoum** [una-dinosauria/human-motion-prediction#16]
Why the start and end joins in viz don't covert all 32 joints?

    self.I   = np.array([1,2,3,1,7,8,1, 13,14,15,14,18,19,14,26,27])-1
    self.J   = np.array([2,3,4,7,8,9,13,14,15,16,18,19,20,26,27,28])-1

**Comment by una-dinosauria** [comment]
Hi @ebarsoum,

Human 3.6M provides 32 joints, but only 17 of them move (the rest are constant displacements). We are only drawing the ones that move.

Cheers,

**Comment by ebarsoum** [comment]
Thanks @una-dinosauria 

Is that because you are training on the angles, so after conversion they are always constant relative to other joints? Did you try to train directly on the 3D joints?

**Comment by una-dinosauria** [comment]
> Is that because you are training on the angles, so after conversion they are always constant relative to other joints?

No. The reason some points are constant offsets is because they

1. give a sense of the person's dimensions (e.g. hand length)
2. act as reference points for degrees of freedom in joints higher up in the kinematic tree. For example, there is a "thumb" at the end of the arms, which by itself has no degrees of freedom; however, its position indications the rotation of the forearm.

> Did you try to train directly on the 3D joints?

No.

**Comment by ebarsoum** [comment]
Thanks again @una-dinosauria
