### ISSUE TITLE
How to visualise a motion from the dataset

### ISSUE THREAD

**Issue by MetaDev** [una-dinosauria/human-motion-prediction#21]
I simply want to visualise a motion from the dataset without having to train a model.
From the flow of your script it is not obvious how to do it, might it be possible to elaborate on how to do it?
Thanks.

**Comment by una-dinosauria** [comment]
Hi @MetaDev,

You can use the [`forward_kinematics.py`](https://github.com/una-dinosauria/human-motion-prediction/blob/master/src/forward_kinematics.py) script almost as is, except you have to read from the `.txt` ground truth files.

Instead of https://github.com/una-dinosauria/human-motion-prediction/blob/c9a2774fe59bb78c6ec6d04e15f2cb7243c4348c/src/forward_kinematics.py#L161-L164

Do something like

```python
  # Read data from .txt file
  data_dir = "./data/h3.6m/dataset"
  test_subject_ids = [5]
  actions = ["walking"]
  one_hot = False
  test_set, _ = data_utils.load_data( data_dir, test_subject_ids, actions, one_hot )

  subject = 5
  subaction = 1
  expmap_gt = test_set[(subject, 'walking', subaction, 'even')]
  # print( expmap_gt, expmap_gt.shape )
  expmap_pred = np.zeros_like( expmap_gt )
```

This will visualize the ground truth for walking.

If you want to see subjects other than 5, you will have to obtain another `offset` (bone lengths) array in ` _some_variables()` from the matlab code that is provided with human3.6M.

Hope that helps!

**Comment by MetaDev** [comment]
That's perfect, thank you for the explanation.

**Comment by MetaDev** [comment]
Hi,

I'm revisiting the data visualization part.
I have seen that not all data is used when visualizing (only 28 joints of
32).
Some joints only contain 0 values but other do seem to have motion.
I tried visualizing them but the result looks weird.
[image: Inline image 1]
I also searched on the 3.6 M dataset website but couldn't find anything on
the names of the joints in the data.
Do you have an idea of what the other joints are?

Thanks.

Best,

Harald

**Comment by una-dinosauria** [comment]
Hi! Do you have the image? It doesn't seem to have been attached.

Re: 28 joints. I believe some of them are repeated. You may want to try plotting a number with text next to the joint and you'll see what I mean.
