### ISSUE TITLE
"forward_only" option is not in Seq2SeqModel.__init__

### ISSUE THREAD

**Issue by Yozey** [una-dinosauria/human-motion-prediction#5]
Hello Julieta, thans for sharing your code, excellent job and paper.

However, i'm wondering if there is an error baseline.py where you initialize the Seq2SeqModel class with a parameter "forward_only" which is not included in Seq2SeqModel.__init__.

Thank you very much:)

**Comment by una-dinosauria** [comment]
Hi @Yozey.

The model creation on `baselines.py` is completely dummy; the baselines are so simple, that we really don't need tensorflow or any model, because we are barely predicting anything. Therefore the parameters that we pass to the model do not matter. See https://github.com/una-dinosauria/human-motion-prediction/blob/master/src/baselines.py#L127

The reason why we create a model in `baselines.py` is because we use its `.get_batch_srnn()` method to get the same exact same data that we use to evaluate the RNN models.

I'm sure this method could be refactored outside the model and it'd save some confusion, but I don't think I'll have time to clean it up myself anytime soon.

I hope that helps!

**Comment by una-dinosauria** [comment]
Oh, sorry, the code wasn't working because of that. I've fixed it now. Sorry about that.

**Comment by una-dinosauria** [comment]
Fixed by 7b19fd3a44c080dd4480eb11542e972824addb
